# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6662e779293f770b81e0bbd530ea3807c742d6117e5cf651b8af06d7bedff6681dae52476cbe7a7180e66fe022d63a00fc82998e84c29434627363859fc5fa3

test:
  secret_key_base: c70485a548da966feffd8abcb39c74e073bb20623a2839d0fcae8947369945f80df6cc6e0d9578165e3a1eb9344b2a2e713f75917e463a9afc724830557e9d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
simulation:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
